@startuml

hide circle
title UML Concept Classes 

Class User {
    login
    password
    email
}

Class TechnicalQuestions {
    purpose
    date
}

Class OfficeEmployee {
    name
}

User"1" --> "*"TechnicalQuestions : send

OfficeEmployee"1" --> "*"TechnicalQuestions : review

@enduml
